# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bot.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'bot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tbot.proto\x12\x03\x62ot\"<\n\x03\x42ot\x12\x0f\n\x07game_id\x18\x01 \x01(\t\x12\x12\n\ndifficulty\x18\x02 \x01(\t\x12\x10\n\x08strategy\x18\x03 \x01(\t\"a\n\x10\x43reateBotRequest\x12\x0e\n\x06\x62ot_id\x18\x01 \x01(\t\x12\x15\n\x03\x62ot\x18\x02 \x01(\x0b\x32\x08.bot.Bot\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x03 \x01(\t\x12\x10\n\x08hostname\x18\x04 \x01(\t\"3\n\x11\x43reateBotResponse\x12\x0e\n\x06\x62ot_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"\"\n\x10\x44\x65leteBotRequest\x12\x0e\n\x06\x62ot_id\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"\x1f\n\rGetBotRequest\x12\x0e\n\x06\x62ot_id\x18\x01 \x01(\t\"x\n\x10ListBotsResponse\x12-\n\x04\x62ots\x18\x01 \x03(\x0b\x32\x1f.bot.ListBotsResponse.BotsEntry\x1a\x35\n\tBotsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x17\n\x05value\x18\x02 \x01(\x0b\x32\x08.bot.Bot:\x02\x38\x01\x32\xd7\x01\n\nBotService\x12<\n\tCreateBot\x12\x15.bot.CreateBotRequest\x1a\x16.bot.CreateBotResponse\"\x00\x12\x30\n\tDeleteBot\x12\x15.bot.DeleteBotRequest\x1a\n.bot.Empty\"\x00\x12(\n\x06GetBot\x12\x12.bot.GetBotRequest\x1a\x08.bot.Bot\"\x00\x12/\n\x08ListBots\x12\n.bot.Empty\x1a\x15.bot.ListBotsResponse\"\x00\x42\x05Z\x03../b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\003../'
  _globals['_LISTBOTSRESPONSE_BOTSENTRY']._loaded_options = None
  _globals['_LISTBOTSRESPONSE_BOTSENTRY']._serialized_options = b'8\001'
  _globals['_BOT']._serialized_start=18
  _globals['_BOT']._serialized_end=78
  _globals['_CREATEBOTREQUEST']._serialized_start=80
  _globals['_CREATEBOTREQUEST']._serialized_end=177
  _globals['_CREATEBOTRESPONSE']._serialized_start=179
  _globals['_CREATEBOTRESPONSE']._serialized_end=230
  _globals['_DELETEBOTREQUEST']._serialized_start=232
  _globals['_DELETEBOTREQUEST']._serialized_end=266
  _globals['_EMPTY']._serialized_start=268
  _globals['_EMPTY']._serialized_end=275
  _globals['_GETBOTREQUEST']._serialized_start=277
  _globals['_GETBOTREQUEST']._serialized_end=308
  _globals['_LISTBOTSRESPONSE']._serialized_start=310
  _globals['_LISTBOTSRESPONSE']._serialized_end=430
  _globals['_LISTBOTSRESPONSE_BOTSENTRY']._serialized_start=377
  _globals['_LISTBOTSRESPONSE_BOTSENTRY']._serialized_end=430
  _globals['_BOTSERVICE']._serialized_start=433
  _globals['_BOTSERVICE']._serialized_end=648
# @@protoc_insertion_point(module_scope)
