# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import bot_pb2 as bot_pb2

class BotServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateBot = channel.unary_unary(
                '/bot.BotService/CreateBot',
                request_serializer=bot_pb2.CreateBotRequest.SerializeToString,
                response_deserializer=bot_pb2.CreateBotResponse.FromString,
                )
        self.DeleteBot = channel.unary_unary(
                '/bot.BotService/DeleteBot',
                request_serializer=bot_pb2.DeleteBotRequest.SerializeToString,
                response_deserializer=bot_pb2.Empty.FromString,
                )
        self.GetBot = channel.unary_unary(
                '/bot.BotService/GetBot',
                request_serializer=bot_pb2.GetBotRequest.SerializeToString,
                response_deserializer=bot_pb2.Bot.FromString,
                )
        self.ListBots = channel.unary_unary(
                '/bot.BotService/ListBots',
                request_serializer=bot_pb2.Empty.SerializeToString,
                response_deserializer=bot_pb2.ListBotsResponse.FromString,
                )


class BotServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateBot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteBot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBots(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateBot': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBot,
                    request_deserializer=bot_pb2.CreateBotRequest.FromString,
                    response_serializer=bot_pb2.CreateBotResponse.SerializeToString,
            ),
            'DeleteBot': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteBot,
                    request_deserializer=bot_pb2.DeleteBotRequest.FromString,
                    response_serializer=bot_pb2.Empty.SerializeToString,
            ),
            'GetBot': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBot,
                    request_deserializer=bot_pb2.GetBotRequest.FromString,
                    response_serializer=bot_pb2.Bot.SerializeToString,
            ),
            'ListBots': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBots,
                    request_deserializer=bot_pb2.Empty.FromString,
                    response_serializer=bot_pb2.ListBotsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bot.BotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))